"""Initial migration

Revision ID: 0a46f6c2c70c
Revises: 
Create Date: 2026-07-09 12:48:36.736977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a46f6c2c70c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bird_count', sa.Integer(), nullable=True),
    sa.Column('bird_age', sa.Integer(), nullable=True),
    sa.Column('t_target', sa.Float(), nullable=True),
    sa.Column('weather_type', sa.String(), nullable=True),
    sa.Column('opt_new', sa.Float(), nullable=True),
    sa.Column('crit_new', sa.Integer(), nullable=True),
    sa.Column('kwh_new', sa.Float(), nullable=True),
    sa.Column('opt_cls', sa.Float(), nullable=True),
    sa.Column('crit_cls', sa.Integer(), nullable=True),
    sa.Column('kwh_cls', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_records_id'), 'simulation_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_records_id'), table_name='simulation_records')
    op.drop_table('simulation_records')
    # ### end Alembic commands ###
